### ISSUE TITLE
Sveltekit support?

### ISSUE THREAD

**Issue by rchrdnsh** [joshnuss/svelte-stripe-js#1]
Apologies if you mentioned it and I missed it, but is sveltekit support included? And if not, does anything need to be altered in any way?

Thanks :-)

**Comment by joshnuss** [comment]
Hi @rchrdnsh!

Thanks for reporting, it should now work with svelte-kit. I'm added notes to the readme here: 
https://github.com/joshnuss/svelte-stripe-js/#svelte-kit

**Comment by rchrdnsh** [comment]
Right on, thanks :-)
