### ISSUE TITLE
using your example I don't have any input fields

### ISSUE THREAD

**Issue by sirugh** [joshnuss/svelte-stripe-js#10]
Code copied directly from your checkout example, I have no inputs. Am I doing something wrong? Apologies if this is obvious, I'm new to svelte :)

[![Image from Gyazo](https://i.gyazo.com/54c1bc751f1cef1e0f53dea0c285046a.png)](https://gyazo.com/54c1bc751f1cef1e0f53dea0c285046a)

```jsx
<script>
	import { Container, CardNumber, CardExpiry, CardCvc, isServer } from 'svelte-stripe-js';

	const stripe = isServer ? null : Stripe(import.meta.env.VITE_STRIPE_PUBLIC_KEY);

	let cardElement;

	async function submit() {
		const result = await stripe.createToken(cardElement);

		// create payment intent
		console.log(result);
	}
</script>

<Container {stripe}>
	<form on:submit|preventDefault={submit}>
		<CardNumber bind:element={cardElement} />
		<CardExpiry />
		<CardCvc />
		<button>Pay</button>
	</form>
</Container>
```

**Comment by sirugh** [comment]
My bad - looks like they're just transparent/unstyled?

**Comment by joshnuss** [comment]
Looks like you figured it out.

I think you're seeing no fields because stripe.js hasn't run, ie when rendering with SSR
