### ISSUE TITLE
Why not use the Stripe.js ES module?

### ISSUE THREAD

**Issue by Bandit** [joshnuss/svelte-stripe-js#12]
I only use Stripe related elements on certain pages of my site, so including StripeJS everywhere seems bad. I saw that Stripe lets you load it as an ES module, and using the `loadStripe` function you can choose when to actually load it. Does this method not work in Sveltekit?

https://github.com/stripe/stripe-js

**Comment by joshnuss** [comment]
Hi @Bandit,

In the readme for stripe/stripe-js it says the script mist be loaded with a script tags to be PCI compliant

> Note: To be PCI compliant, you must load Stripe.js directly from https://js.stripe.com. You cannot include it in a bundle or host it yourself. This package wraps the global Stripe function provided by the Stripe.js script as an ES module.

But you can have a separate layout for your checkout pages and include the script using `<svelte:head>` instead of setting it globally in `app.html`

**Comment by Bandit** [comment]
Yeah I read that part - but then the `loadStripe` function mentions injecting the script tag?

> By default, this module will insert a <script> tag that loads Stripe.js from https://js.stripe.com. This happens as a side effect immediately upon importing this module. If you utilize code splitting or only include your JavaScript app on your checkout page, the Stripe.js script will only be available in parts of your site.

**Comment by joshnuss** [comment]
You're totally right. I'm going to update the README examples to use `await loadStripe()`.

The only hitch is it requires initializing stripe in the `onMount()`, since `loadStripe()` is async.

Thanks for pointing this out :+1:

**Comment by Bandit** [comment]
Not possible to pass the Stripe key to `<Container>` and have it boilerplate the `onMount` and `loadStripe` etc?

**Comment by joshnuss** [comment]
It's possible, but how would user code get access to `stripe`?  It's still up to the user to interface with stripe (ie`stripe.confirmCardPayment()`, et al). If the `<Container>` initializes the `Stripe` instance, it would need to share it somehow. Not sure if that makes it simpler.

**Comment by Bandit** [comment]
I haven't spent much time thinking about it, but why not something like

`<Container bind:stripe>`

As a two-way binding, where `Container` overrides the `stripe` variable `onMount`?

Another option would be `setContext` from the `Container` and `getContext` from consuming child components (which is better in terms of not having to pass the same `stripe` variable all the way down the chain if you have a complex web of components)

Anyway just some thoughts 😁

**Comment by joshnuss** [comment]
Yeah, I considered `bind:stripe`, but feels odd that the container owns the `stripe` instance, I rather the client own that. This is just a UI libary, so not sure if it should be responsible for that.

The problem with with `setContext` is that it must be called in the root of the component (outside `onMount()`). But `loadStripe()` is async and can only be called from within an `async` method.  I tried  doing that in an async `onMount`, but you can't call `setContext()` inside `onMount()`, Svelte throws an error.

**Comment by Bandit** [comment]
> It might be possible by wrapping the stripe instance with a store, and placing that in the context

Yeah this is how you do it. I do this with my Firebase user sessions (which are loaded from an async callback)

**Comment by joshnuss** [comment]
At this stage I prefer to support one approach only, otherwise I have to explain that in the docs. It just adds complexity imo.

I rather the user own the stripe instance and pass it in.

If I have time down the road, I'll look at adding stores to context, or if you need it sooner, feel free to open a PR.
