### ISSUE TITLE
kit 234 might not work with mkcert anymore...

### ISSUE THREAD

**Issue by rchrdnsh** [joshnuss/svelte-stripe-js#18]
Here is a thread on the svelte discord server about the issue for you information...not sure how to proceed with setting up https anymore for testing in dev environments...

https://discord.com/channels/457912077277855764/933925500575940648

and happy new year! XD

**Comment by joshnuss** [comment]
I opened an issue with svelte-kit related to https option:
https://github.com/sveltejs/kit/issues/3479

**Comment by rchrdnsh** [comment]
Oh, great, glad you're up on it :-)

**Comment by rchrdnsh** [comment]
yay, it's all working again...let's close this out then :-)
