### ISSUE TITLE
How to retrieve/input/use products and prices from stripe...

### ISSUE THREAD

**Issue by rchrdnsh** [joshnuss/svelte-stripe-js#19]
So,

Trying to read through the stripe docs but unclear about how I might go about retrieving/inputting/using stripe products and prices using SvelteKit. Just curious if you have thought about this at all and/or have any solutions to this kind of thing...it's one thing to manually add one price point, but another thing to integrate with products and prices from the stripe dashboard/account...

Thank you! XD

**Comment by rchrdnsh** [comment]
Starting by trying to do something like this, based on the API docs I've been able to find:

```js
import dotenv from 'dotenv';
dotenv.config();

import Stripe from 'stripe';
const stripe = new Stripe(process.env['STRIPE_SECRET_TEST_KEY']);

export async function post() {
  const product = await stripe.products.retrieve(
    'prod_aBcDeFgHiJ123456789'
  )

  return {
    body: {
      content: product
    }
  }
};
```

...dunno if any of this will work or not...

If you have any thoughts or experience with this, please share :-)

**Comment by joshnuss** [comment]
Hey Richard,

As long as you use the product as part of the payment intent it will work.

To attach a product to a payment intent, first create an invoice. [Example](https://stackoverflow.com/a/68442645/306520).

Tip: if the `/products` endpoint depends on calling Stripe, it could get rate limited when there's tons of traffic. So maybe cache the results for a few minutes?

**Comment by rchrdnsh** [comment]
hmmmm...

I'm only trying to offer people different donations amounts to choose from...maybe there is a simpler way...

This is is the UI:

<img width="807" alt="Screen Shot 2022-01-29 at 6 47 21 PM" src="https://user-images.githubusercontent.com/7884263/151684770-b36507a7-3d88-4475-aa87-647ebee78277.png">

...gonna need to work through some more docs, I guess...

**Comment by joshnuss** [comment]
I see, so maybe using a product isn't needed here.

The payment intent could be created based an amount. I would create an endpoint that:

1. takes `amount` as a param
2. creates the payment intent using the provided `amount`
3. returns the payment intent's client secret

Then you can pass that client secret to the `<PaymentElement/>`

It's very similar to [this example](https://svelte-stripe-js.vercel.app/#creating-a-payment-intent) just that the `amount` is based on `params.get('amount')`.

**Comment by rchrdnsh** [comment]
You know, I'm realizing that I simply don't understand endpoints and loading, etc. in svelte kit and in node and on servers in general...I just don't know how to do any of this and make it work because I don't understand what's going on, as I have 0 experience with any of it.

for example, I simply don't know how to add the params thing in here to make it work:

```js
import dotenv from 'dotenv';
dotenv.config();

import Stripe from 'stripe';
const stripe = new Stripe(process.env['STRIPE_SECRET_TEST_KEY']);

export async function post({ params }) {
  // let amount = params.get('amount'); Like this?
  const paymentIntent = await stripe.paymentIntents.create({
    // amount: params.get('amount'), or like this?
    amount: 999,
    // amount, reference it like this?
    currency: 'usd',
    automatic_payment_methods: {
      enabled: true,
    }
  });

  return {
    body: {
      clientSecret: paymentIntent.client_secret
    }
  };
};
```
...none of these seem to work as they come back as an error that `params.get is not a function` and `Unexpected token < in JSON at position 0` and i don't know how to access an amount variables in the load function on the page either...

```js
<script context='module'>
  export async function load({ fetch, params }) {
    // create payment intent
    const response = await fetch('/api/payment-intent', {
      method: 'POST',
      headers: {
        'content-type': 'application/json'
      },
      body: JSON.stringify({amount: 999}) // what do I do here to access an amount variable that the user can change
    })
    const { clientSecret } = await response.json()
    // share payment intent's client secret
    return {
      props: {
        clientSecret
      }
    }
  }
</script>
```
...and I don't have enough experience reading docs to be able to understand them...I look at the svelte docs and it all looks so foreign to me, since I am new to all of this stuff...

I keep goggling around but I am not even sure what to google to help me because I do not really know what it is that I am missing in my understanding...

I'll try asking on the discord and maybe I can put it together in my head better if I formulate my questions more generally :-)

**Comment by joshnuss** [comment]
Oh, I may have given you incorrect advice, the endpoint should get the `amount` from `body` instead of `params`. 
See: https://kit.svelte.dev/docs#routing-endpoints-body-parsing

If you'd like some help, I'd be happy to jump on a Zoom and help figure it out.

**Comment by joshnuss** [comment]
Hey Richard!

Just checking in to see if this is still and issue or have you been able to resolve it?

**Comment by joshnuss** [comment]
Hi Richard, 

I think my explanation above answers the question. Feel free to re-open the issue if you have further questions. Or post a question in the [discussions](https://github.com/joshnuss/svelte-stripe-js/discussions)
