### ISSUE TITLE
New beta Stripe elements…

### ISSUE THREAD

**Issue by rchrdnsh** [joshnuss/svelte-stripe-js#2]
Dunno if you know or not, but stripe recently announced new stripe elements that are currently in beta:

https://stripe.com/docs/payments/payment-element

Apologies if you already knew :-)

**Comment by joshnuss** [comment]
Thanks for sharing @rchrdnsh! Did not know about this.

I signed up for the beta

 I imagine it could be just another component, ie `<PaymentElement {options}/>` just like their React example.

**Comment by rchrdnsh** [comment]
I believe it was mentioned somewhere that there are plans to alter and/or update and/or expand elements, but I'm sure they'll fill you in more when you hop into the beta :-)

**Comment by rchrdnsh** [comment]
Looks like the new payment element is out now :-)

`https://stripe.com/docs/payments/payment-element`

**Comment by joshnuss** [comment]
Yes, heard it was out of Beta. Will have to add it 🙂

**Comment by joshnuss** [comment]
@rchrdnsh thanks for making me aware of this one!

Docs: https://svelte-stripe-js.vercel.app/#payment-element
Demo: https://svelte-stripe-js.vercel.app/examples/payment-element
Code example: https://github.com/joshnuss/svelte-stripe-js/blob/6291a5adbf8fba675b5f0a67d1cfe717f59b76ae/src/routes/examples/payment-element/index.svelte#L74

**Comment by rchrdnsh** [comment]
woo hoo! thank yooooooo :-)
