### ISSUE TITLE
Passing metadata into stripe paymentIntent 

### ISSUE THREAD

**Issue by LucasRitossa** [joshnuss/svelte-stripe-js#25]
Hello, I followed the docs until I ran into this issue with the paymentIntent flow. I need the ability to pass data from a svelte store into my paymentIntent post request, but this is not possible in a svelte module context. Is there any way to achieve this?
```js
export async function load({ fetch }) {
  const response = await fetch('createPaymentIntent', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ metadata, session })
  })
  const { clientSecret } = await response.json()
  console.log(clientSecret)
  return {
    props: {
      clientSecret
    }
  }
}                     
```

**Comment by joshnuss** [comment]
Hi Lucas!

Creating the payment intent can be done outside the module context too. For example, during `onMount`, or during an event like `on:click`.

Let me know if that solves it

**Comment by LucasRitossa** [comment]
Hey, thanks for the response. 
I solved my issue using the `onMount()` function. It might be worth documenting the paymentIntent endpoint must be requested before the `loadStripe()` function is declared.

Thanks!

**Comment by joshnuss** [comment]
Thanks for the update, glad you got it working.

I think it's ok if `loadStripe` is called first. The payment intent can be created after user enters payment info, for example when the user clicks the "Pay"/"Checkout" button

**Comment by LucasRitossa** [comment]
Ah, I only mentioned that because in my testing `loadStripe` needed to be called after the paymentIntent, or else the stripe components would error out.

**Comment by joshnuss** [comment]
The Stripe components do need access to the `stripe` instance, but the payment intent can be created later.

You may have to conditionally hide the Stripe components until you have a `stripe` instance though, ie

```html
{#if stripe}
  <-- components here -->
{/if}
```

**Comment by joshnuss** [comment]
[I've updated the docs](d6b7da7d6e3600b9d3213ee955436cdd886f33be) to create the Payment Intent outside `<script context="module">`.  I believe it better illustrates how it should work in a real app.

Thanks for the feedback @LucasRitossa :raised_hands:

**Comment by LucasRitossa** [comment]
Awesome, that seems like a great change. Thanks for all the help and great library 👍
