### ISSUE TITLE
Add Demo to README

### ISSUE THREAD

**Issue by rotimi-best** [joshnuss/svelte-stripe-js#3]
Maybe it would be a good idea to add a demo to the README, in order for everyone to know what how it would look once they add this library to their application

**Comment by joshnuss** [comment]
:100: 

I plan to create a demo site, with the following demos:

- One time payment
- Subscription payment
- Payment request button (ApplePay/GPay)
- SEPA direct deposit
- iDEAL

Hopefully over the next week or so :crossed_fingers:

**Comment by rotimi-best** [comment]
Great, thank you.

**Comment by rotimi-best** [comment]
I think I should reopen it, and we can consider it closed once the Demo has been added. Thank you

**Comment by joshnuss** [comment]
Hi,

First version of the docs site is live here:
https://svelte-stripe-js.vercel.app

Closing for now, but feel free to open issues & PRs about specific docs issues.
