### ISSUE TITLE
ENV VAR's for stripe keys...

### ISSUE THREAD

**Issue by rchrdnsh** [joshnuss/svelte-stripe-js#6]
So, in the docs the examples show the test key in the `.svelte` file, but this does not seem to be the best idea, no?

I would assume they should be in ENV VAR's on the server and fed into the component...just don't quite know how to do that myself...and putting it into the component file itself means that it will be seen by github, which does not seem like a good idea, I think.

So this isn't an issue with the library directly, but rather a question as to how to go about using ENV Var's in the context of this library...I don't really know, but I believe that using VITe's built-in environment variables is not recommended for secret keys...

...curious if you have some suggestions as to what the best way to go about this would be...

**Comment by joshnuss** [comment]
Good points. 

It should come from the environment variables. But the key that starts with `pk_`  means "public key", so it's allowed to be shared with the client/browser. Where as secret keys that start with `sk_`, should only be used on the server side in a trusted environment.

With vite, shareable (public) environment vars start with `VITE_`, so you can create a a file `.env`:

```
VITE_STRIPE_PUBLIC_KEY=pk_your_key_here
```

Then when you initialize stripe, it would use `import.meta.env.VITE_STRIPE_PUBLIC_KEY`

```javascript
const stripe = isServer ? null : Stripe(import.meta.env.VITE_STRIPE_PUBLIC_KEY)
```

**Comment by joshnuss** [comment]
I updated the README, 

Let me know if you run into anything! I hope to create an example site at some point.

**Comment by jonathanstanley** [comment]
Just to shed some light on a similar concern. I noticed an example that showed secrets in the client-side code.

https://github.com/joshnuss/svelte-stripe/blob/2375ab8234b72d0ee96685ebce7252f0338c2c77/src/routes/examples/payment-element/%2Bpage.svelte#L9

From there, I noticed the server-side code returns a secret to the client:

https://github.com/joshnuss/svelte-stripe/blob/2375ab8234b72d0ee96685ebce7252f0338c2c77/src/routes/examples/payment-element/payment-intent/%2Bserver.js#L16-L18

Thought it was a security issue, but realized [`client_secret` is Stripe's naming convention and can be used client-side](https://github.com/stripe/stripe-node/blob/f91a8f4e3fba03e1cd01c082f190aac74b55758c/types/PaymentIntents.d.ts#L76-L83).
