### ISSUE TITLE
Need to add a style object...unclear how...

### ISSUE THREAD

**Issue by rchrdnsh** [joshnuss/svelte-stripe-js#7]
I need to style the elements, something along these lines...

```js
  let style = {
    base: {
      padding: '8px',
      color: '#ffffff',
      fontFamily: 'Avenir Next',
      fontSmoothing: 'antialiased',
      fontSize: '16px',
      '::placeholder': {
        color: '#aaaaaa'
      },
    },
    invalid: {
      color: '#fa755a',
    }
  };
```

but I'm unclear as to how to do that in this library.

One does something like this usually:

```js
let idealBank = elements.create('idealBank', {style: style});
```
...but unclear as to how to do this using the library :-)

**Comment by joshnuss** [comment]
Hey @rchrdnsh,

All components take `style` and `classes` attributes, they follow the same structure outlined in stripe's docs.

So you can do:

```html
<!-- pass style attribute -->
<Iban {style}/>

<!-- or with classes -->
<Iban {classes}/>
```

Hopefully I will have some time over the next few weeks to put together a documentation site with some styled examples.

**Comment by rchrdnsh** [comment]
yay, that worked just fine for me, thanks :-)
